import type {Metadata} from 'next';
import './globals.css';
import Providers from "@/app/provider";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="flex min-h-screen flex-col">
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}
