import type {Metadata} from 'next';
import './globals.css';
import ReduxProvider from '@/app/provider/ReduxProvider';
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from "@/app/provider/AuthProvider";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="flex min-h-screen flex-col">
        <ReduxProvider>
            <AuthProvider>
                {children}
                <ToastContainer position="top-right" autoClose={3000}/>
            </AuthProvider>
        </ReduxProvider>
        </body>
        </html>
    );
}
